export enum PRIMARY_CATEGORY {
  BACKEND = "backend",
  FRONTEND = "frontend",
  DEVOPS = "devops",
  DATABASE = "database",
  ARCHITECTURE = "architecture",
  AI_ML = "ai_ml",
  BLOCKCHAIN = "blockchain",
  SECURITY = "security",
  TESTING = "testing",
  SYSTEM_DESIGN = "system_design",
  PRODUCT = "product",
  CAREER = "career",
  RESEARCH = "research",
  OTHER = "other",
}

export enum PERSONALITIES {
  CALM = "calm",
  AGGRESSIVE = "aggressive",
  ANALYTICAL = "analytical",
  CREATIVE = "creative",
  LOGICAL = "logical",
  INTUITIVE = "intuitive",
  PRACTICAL = "practical",
  THEORETICAL = "theoretical",
  EMPATHETIC = "empathetic",
  DIRECT = "direct",
  PATIENT = "patient",
  ENTHUSIASTIC = "enthusiastic",
  SCEPTICAL = "sceptical",
  SUPPORTIVE = "supportive",
  HUMOROUS = "humorous",
  FORMAL = "formal",
  CASUAL = "casual",
  MINIMALIST = "minimalist",
  THOROUGH = "thorough",
}
