export enum TOOL_TYPE {
  WEB_SEARCH = "web_search",
  SEND_EMAIL = "send_email",
  CALENDAR_READ = "calendar_read",
  CALENDAR_WRITE = "calendar_write",
  REMINDER_SET = "reminder_set",
  REMINDER_LIST = "reminder_list",
  WEATHER = "weather",
  CODE_EXECUTION = "code_execution",
  FILE_READ = "file_read",
  FILE_WRITE = "file_write",
  HTTP_REQUEST = "http_request",
  RETRIEVE_USER_MEMORY = "retrieve_user_memory",
  STORE_USER_MEMORY = "store_user_memory",
}
